import {
  createNormalizedCoordinateResult,
  createWarningMetadata,
  RECOGNIZER_PORT_STATUS,
  RECOGNIZER_TYPES,
  validateNormalizedCoordinateResult,
} from "./contracts.js";
import { createLatencyBudget, allocateRecognizerBudget } from "./latency-budget.js";
import { createRecognizerContract } from "./recognizer-contract.js";
import { createDefaultRecognizerRegistry, getRecognizerRegistrySummary, validateRecognizerRegistry } from "./registry.js";
import { runCoordinateEngineV3, V3_RUNNER_STATUS } from "./runner.js";
import {
  canHandleCoteDivoireDms,
  COTE_DIVOIRE_DMS_CRS,
  COTE_DIVOIRE_DMS_PRECISION_MODE,
  COTE_DIVOIRE_DMS_RECOGNIZER_ID,
  coteDivoireDmsRecognizer,
  normalizeCoteDivoireDms,
  parseCoteDivoireDmsTable,
  recognizeCoteDivoireDms,
  toCoteDivoireDmsKmlCoordinate,
  verifyCoteDivoireDms,
} from "./recognizers/cote-divoire-dms/index.js";
import {
  canHandleDmsGroupedCoordinates,
  DMS_GROUPED_COORDINATES_CRS,
  DMS_GROUPED_COORDINATES_PRECISION_MODE,
  DMS_GROUPED_COORDINATES_RECOGNIZER_ID,
  dmsGroupedCoordinatesRecognizer,
  normalizeDmsGroupedCoordinates,
  parseDmsGroupedCoordinates,
  recognizeDmsGroupedCoordinates,
  toDmsGroupedCoordinatesKmlCoordinate,
  verifyDmsGroupedCoordinates,
} from "./recognizers/dms-grouped-coordinates/index.js";
import {
  canHandleGenericDms,
  dmsToDecimal,
  genericDmsRecognizer,
  normalizeGenericDms,
  parseDmsTokens,
  parseGenericDmsRows,
  recognizeGenericDms,
  toGenericDmsKmlCoordinate,
  verifyGenericDms,
} from "./recognizers/generic-dms/index.js";
import {
  buildIndonesiaUtmVerification,
  canHandleIndonesiaUtm,
  INDONESIA_UTM_OUTPUT_CRS,
  INDONESIA_UTM_PRECISION_MODE,
  INDONESIA_UTM_RECOGNIZER_ID,
  INDONESIA_UTM_SOURCE_CRS,
  INDONESIA_UTM_VERIFICATION_TOLERANCE,
  indonesiaUtmRecognizer,
  normalizeIndonesiaUtm,
  parseIndonesiaUtmTable,
  recognizeIndonesiaUtm,
  toIndonesiaUtmKmlCoordinate,
  transformIndonesiaUtmPoint,
  transformIndonesiaUtmRows,
  verifyIndonesiaUtm,
} from "./recognizers/indonesia-utm/index.js";
import {
  canHandleKyrgyzGk,
  convertKyrgyzGkToWgs84,
  KYRGYZ_GK_CRS,
  KYRGYZ_GK_PRECISION_MODE,
  kyrgyzGkRecognizer,
  looksLikeKyrgyzGkPair,
  normalizeKyrgyzGk,
  parseKyrgyzGkRows,
  recognizeKyrgyzGk,
  toKyrgyzGkKmlCoordinate,
  verifyKyrgyzGk,
} from "./recognizers/kyrgyzstan-gauss-kruger/index.js";
import {
  buildMadagascarCadastralCellPolygons,
  canHandleMadagascarCadastral,
  convertMadagascarCadastralToWgs84,
  formatMadagascarCadastralRows,
  inferMadagascarCadastralCellGeometry,
  MADAGASCAR_CADASTRAL_CELL_SEMANTICS,
  MADAGASCAR_CADASTRAL_OUTPUT_CRS,
  MADAGASCAR_CADASTRAL_PRECISION_MODE,
  MADAGASCAR_CADASTRAL_RECOGNIZER_ID,
  MADAGASCAR_CADASTRAL_SOURCE_CRS,
  madagascarCadastralRecognizer,
  normalizeMadagascarCadastral,
  parseMadagascarCadastralRows,
  recognizeMadagascarCadastral,
  toMadagascarCadastralKmlCoordinate,
  verifyMadagascarCadastral,
} from "./recognizers/madagascar-cadastral/index.js";
import {
  canHandleMgrs,
  mgrsRecognizer,
  normalizeMgrs,
  parseMgrsRows,
  recognizeMgrs,
  toMgrsKmlCoordinate,
  verifyMgrs,
} from "./recognizers/mgrs/index.js";
import {
  canHandleWgs84Decimal,
  normalizeWgs84Decimal,
  recognizeWgs84Decimal,
  toKmlCoordinate,
  verifyWgs84Decimal,
  wgs84DecimalRecognizer,
} from "./recognizers/wgs84-decimal/index.js";
import {
  canHandleWgs84Table,
  normalizeWgs84Table,
  parseWgs84Table,
  recognizeWgs84Table,
  toWgs84TableKmlCoordinate,
  verifyWgs84Table,
  WGS84_TABLE_CRS,
  WGS84_TABLE_PRECISION_MODE,
  WGS84_TABLE_RECOGNIZER_ID,
  wgs84TableRecognizer,
} from "./recognizers/wgs84-table/index.js";
export {
  ACQUISITION_ADAPTER_STATUS,
  ACQUISITION_AUTHORITY_FIELDS,
  ACQUISITION_CANDIDATE_SCHEMA_VERSION,
  ACQUISITION_HARD_DEADLINE_MS,
  ACQUISITION_MAX_PROVIDER_CALLS,
  ACQUISITION_PROVENANCE,
  ACQUISITION_SCHEMA_VERSION,
  ACQUISITION_SENSITIVE_FIELDS,
  ACQUISITION_SOURCE_TYPE,
  ACQUISITION_STATUS,
  ACQUISITION_TARGET_MS,
  acquisitionCandidateToRunnerInput,
  PRIMARY_ACQUISITION_ERROR,
  PRIMARY_ACQUISITION_MAX_PROVIDER_CALLS,
  PRIMARY_ACQUISITION_PROMPT,
  PRIMARY_ACQUISITION_PROVIDER_TIMEOUT_MS,
  ACQUISITION_STRATEGY_ID,
  ACQUISITION_STRATEGY_INPUT_MODE,
  ACQUISITION_STRATEGY_MODEL,
  ACQUISITION_STRATEGY_REASON,
  EXPERIMENTAL_STRUCTURAL_ROUTER_CONTRACT,
  EXPERIMENTAL_STRUCTURAL_ROUTER_THRESHOLDS,
  TABLE_CONTEXT_COMPOSITE_MODE,
  TABLE_CONTEXT_COMPOSITE_STATUS,
  acquirePrimaryImage,
  calculateCandidateCompleteness,
  chooseAcquisitionStrategyFromMetrics,
  callPrimaryVisionProvider,
  createTableContextComposite,
  createAcquisitionAdapterMetrics,
  createAcquisitionBudget,
  createAcquisitionCandidate,
  createAcquisitionResult,
  dedupeAcquisitionCandidates,
  detectTableContextRegions,
  dryRunAcquisitionStrategy,
  getPrimaryProviderReadiness,
  getCandidateDedupeKey,
  normalizeStructuralMetrics,
  runAcquisitionCandidatesThroughRunner,
  shouldRequestTargetedAcquisition,
  stripSensitiveAcquisitionMetadata,
  validateAcquisitionCandidate,
  validateAcquisitionResult,
} from "./acquisition/index.js";

export {
  chooseV3ProductionReason,
  buildCoordinateEngineV3ProductionShadow,
  buildV3FamilyCanarySelection,
  buildV3ShadowEvaluationMetric,
  getV3ProductionScopeStatus,
  isWgs84DecimalCanaryEnabled,
  isV3ProductionSupported,
  mapV3ProductionResult,
  recordV3ShadowEvaluationMetric,
  V3_CANARY_SELECTED_ENGINE,
  V3_CANARY_SELECTION_REASON,
  V3_CANARY_SELECTION_SCHEMA_VERSION,
  V3_PRODUCTION_REASON_CODE,
  V3_PRODUCTION_REASON_PRIORITY,
  V3_PRODUCTION_RESULT_SCHEMA_VERSION,
  V3_PRODUCTION_SCOPE_STATUS,
  V3_PRODUCTION_STATUS,
  V3_PRODUCTION_SUPPORTED_SCOPE_V1,
  V3_TECHNICAL_KML_HARD_BLOCK_REASONS,
  WGS84_DECIMAL_CANARY_FAMILY,
  WGS84_DECIMAL_CANARY_FLAG,
} from "./production/index.js";

export const COORDINATE_ENGINE_V3_DISABLED_REASON = "coordinate_engine_v3_not_enabled";

export function isCoordinateEngineV3Enabled(env = process.env) {
  return String(env.ENABLE_COORDINATE_ENGINE_V3 || "").trim().toLowerCase() === "true";
}

export async function recognizeWithIsolatedRecognizers(input = {}, {
  env = process.env,
  registry = createDefaultRecognizerRegistry(),
  latencyBudget = createLatencyBudget(),
} = {}) {
  if (!isCoordinateEngineV3Enabled(env)) {
    return Object.freeze({
      handled: false,
      reason: COORDINATE_ENGINE_V3_DISABLED_REASON,
      registry: getRecognizerRegistrySummary(registry),
    });
  }

  return runCoordinateEngineV3(input, { registry, latencyBudget });
}

export {
  allocateRecognizerBudget,
  createDefaultRecognizerRegistry,
  createLatencyBudget,
  createRecognizerContract,
  createNormalizedCoordinateResult,
  createWarningMetadata,
  getRecognizerRegistrySummary,
  runCoordinateEngineV3,
  RECOGNIZER_PORT_STATUS,
  RECOGNIZER_TYPES,
  validateNormalizedCoordinateResult,
  validateRecognizerRegistry,
  V3_RUNNER_STATUS,
  canHandleCoteDivoireDms,
  COTE_DIVOIRE_DMS_CRS,
  COTE_DIVOIRE_DMS_PRECISION_MODE,
  COTE_DIVOIRE_DMS_RECOGNIZER_ID,
  coteDivoireDmsRecognizer,
  normalizeCoteDivoireDms,
  parseCoteDivoireDmsTable,
  recognizeCoteDivoireDms,
  toCoteDivoireDmsKmlCoordinate,
  verifyCoteDivoireDms,
  canHandleDmsGroupedCoordinates,
  DMS_GROUPED_COORDINATES_CRS,
  DMS_GROUPED_COORDINATES_PRECISION_MODE,
  DMS_GROUPED_COORDINATES_RECOGNIZER_ID,
  dmsGroupedCoordinatesRecognizer,
  normalizeDmsGroupedCoordinates,
  parseDmsGroupedCoordinates,
  recognizeDmsGroupedCoordinates,
  toDmsGroupedCoordinatesKmlCoordinate,
  verifyDmsGroupedCoordinates,
  canHandleGenericDms,
  dmsToDecimal,
  genericDmsRecognizer,
  normalizeGenericDms,
  parseDmsTokens,
  parseGenericDmsRows,
  recognizeGenericDms,
  toGenericDmsKmlCoordinate,
  verifyGenericDms,
  buildIndonesiaUtmVerification,
  canHandleIndonesiaUtm,
  INDONESIA_UTM_OUTPUT_CRS,
  INDONESIA_UTM_PRECISION_MODE,
  INDONESIA_UTM_RECOGNIZER_ID,
  INDONESIA_UTM_SOURCE_CRS,
  INDONESIA_UTM_VERIFICATION_TOLERANCE,
  indonesiaUtmRecognizer,
  normalizeIndonesiaUtm,
  parseIndonesiaUtmTable,
  recognizeIndonesiaUtm,
  toIndonesiaUtmKmlCoordinate,
  transformIndonesiaUtmPoint,
  transformIndonesiaUtmRows,
  verifyIndonesiaUtm,
  canHandleKyrgyzGk,
  convertKyrgyzGkToWgs84,
  KYRGYZ_GK_CRS,
  KYRGYZ_GK_PRECISION_MODE,
  kyrgyzGkRecognizer,
  looksLikeKyrgyzGkPair,
  normalizeKyrgyzGk,
  parseKyrgyzGkRows,
  recognizeKyrgyzGk,
  toKyrgyzGkKmlCoordinate,
  verifyKyrgyzGk,
  buildMadagascarCadastralCellPolygons,
  canHandleMadagascarCadastral,
  convertMadagascarCadastralToWgs84,
  formatMadagascarCadastralRows,
  inferMadagascarCadastralCellGeometry,
  MADAGASCAR_CADASTRAL_CELL_SEMANTICS,
  MADAGASCAR_CADASTRAL_OUTPUT_CRS,
  MADAGASCAR_CADASTRAL_PRECISION_MODE,
  MADAGASCAR_CADASTRAL_RECOGNIZER_ID,
  MADAGASCAR_CADASTRAL_SOURCE_CRS,
  madagascarCadastralRecognizer,
  normalizeMadagascarCadastral,
  parseMadagascarCadastralRows,
  recognizeMadagascarCadastral,
  toMadagascarCadastralKmlCoordinate,
  verifyMadagascarCadastral,
  canHandleMgrs,
  mgrsRecognizer,
  normalizeMgrs,
  parseMgrsRows,
  recognizeMgrs,
  toMgrsKmlCoordinate,
  verifyMgrs,
  canHandleWgs84Decimal,
  normalizeWgs84Decimal,
  recognizeWgs84Decimal,
  toKmlCoordinate,
  verifyWgs84Decimal,
  wgs84DecimalRecognizer,
  canHandleWgs84Table,
  normalizeWgs84Table,
  parseWgs84Table,
  recognizeWgs84Table,
  toWgs84TableKmlCoordinate,
  verifyWgs84Table,
  WGS84_TABLE_CRS,
  WGS84_TABLE_PRECISION_MODE,
  WGS84_TABLE_RECOGNIZER_ID,
  wgs84TableRecognizer,
};
