export const V3_PRODUCTION_RESULT_SCHEMA_VERSION = "coordinate_engine_v3_production_result_v1";

export const V3_PRODUCTION_STATUS = Object.freeze({
  SUCCESS: "SUCCESS",
  REVIEW_REQUIRED: "REVIEW_REQUIRED",
  UNSUPPORTED: "UNSUPPORTED",
});

export const V3_PRODUCTION_REASON_CODE = Object.freeze({
  INCOMPLETE_EXTRACTION: "INCOMPLETE_EXTRACTION",
  RECOGNIZER_NOT_AVAILABLE: "RECOGNIZER_NOT_AVAILABLE",
  AMBIGUOUS_COORDINATE_SYSTEM: "AMBIGUOUS_COORDINATE_SYSTEM",
  AMBIGUOUS_RECOGNIZER: "AMBIGUOUS_RECOGNIZER",
  CANDIDATE_CONFLICT: "CANDIDATE_CONFLICT",
  PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",
  LOW_CONFIDENCE: "LOW_CONFIDENCE",
  PARTIAL_ROWS_RECOVERED: "PARTIAL_ROWS_RECOVERED",
  EXPERIMENTAL_PATH_REQUIRED: "EXPERIMENTAL_PATH_REQUIRED",
  UNVERIFIED_PRODUCTION_SCOPE: "UNVERIFIED_PRODUCTION_SCOPE",
  NO_USABLE_CANDIDATE: "NO_USABLE_CANDIDATE",
  UNSUPPORTED_COORDINATE_TYPE: "UNSUPPORTED_COORDINATE_TYPE",
  NO_NORMALIZED_COORDINATES: "NO_NORMALIZED_COORDINATES",
  INVALID_COORDINATE_STRUCTURE: "INVALID_COORDINATE_STRUCTURE",
  INVALID_GEOMETRY: "INVALID_GEOMETRY",
  UNSUPPORTED_PRODUCTION_SCOPE: "UNSUPPORTED_PRODUCTION_SCOPE",
});

export const V3_TECHNICAL_KML_HARD_BLOCK_REASONS = Object.freeze({
  NO_COORDINATES: "NO_COORDINATES",
  NON_NUMERIC_COORDINATES: "NON_NUMERIC_COORDINATES",
  INSUFFICIENT_DATA_FOR_REQUESTED_GEOMETRY: "INSUFFICIENT_DATA_FOR_REQUESTED_GEOMETRY",
  UNPARSABLE_COORDINATE_STRUCTURE: "UNPARSABLE_COORDINATE_STRUCTURE",
  INVALID_GEOMETRY: "INVALID_GEOMETRY",
});

export const V3_PRODUCTION_REASON_PRIORITY = Object.freeze([
  V3_PRODUCTION_REASON_CODE.NO_USABLE_CANDIDATE,
  V3_PRODUCTION_REASON_CODE.INVALID_COORDINATE_STRUCTURE,
  V3_PRODUCTION_REASON_CODE.INVALID_GEOMETRY,
  V3_PRODUCTION_REASON_CODE.INCOMPLETE_EXTRACTION,
  V3_PRODUCTION_REASON_CODE.PARTIAL_ROWS_RECOVERED,
  V3_PRODUCTION_REASON_CODE.CANDIDATE_CONFLICT,
  V3_PRODUCTION_REASON_CODE.AMBIGUOUS_RECOGNIZER,
  V3_PRODUCTION_REASON_CODE.AMBIGUOUS_COORDINATE_SYSTEM,
  V3_PRODUCTION_REASON_CODE.RECOGNIZER_NOT_AVAILABLE,
  V3_PRODUCTION_REASON_CODE.PROVIDER_TIMEOUT,
  V3_PRODUCTION_REASON_CODE.EXPERIMENTAL_PATH_REQUIRED,
  V3_PRODUCTION_REASON_CODE.UNSUPPORTED_COORDINATE_TYPE,
  V3_PRODUCTION_REASON_CODE.NO_NORMALIZED_COORDINATES,
  V3_PRODUCTION_REASON_CODE.UNSUPPORTED_PRODUCTION_SCOPE,
  V3_PRODUCTION_REASON_CODE.UNVERIFIED_PRODUCTION_SCOPE,
  V3_PRODUCTION_REASON_CODE.LOW_CONFIDENCE,
]);
