export const FINALIZED_COORDINATE_SCHEMA_VERSION = "finalized_coordinate_result_v1";
export const CONFIRMATION_RUNTIME_VERSION = "coordinate_confirmation_runtime_v1";

export const COORDINATE_DECISION_STATE = Object.freeze({
  AUTO_EXPORT: "AUTO_EXPORT",
  REVIEW_REQUIRED: "REVIEW_REQUIRED",
  BLOCKED: "BLOCKED"
});

export const COORDINATE_CONFIRMATION_STATUS = Object.freeze({
  NOT_REQUIRED: "not_required",
  PENDING: "pending",
  ACCEPTED: "accepted",
  REJECTED: "rejected"
});

export const COORDINATE_QUALITY_GATE_STATUS = Object.freeze({
  PASSED: "passed",
  REVIEW_REQUIRED: "review_required",
  FAILED: "failed",
  UNKNOWN: "unknown"
});

export const COORDINATE_GATE_REASON = Object.freeze({
  CONFIRMATION_REQUIRED: "CONFIRMATION_REQUIRED",
  CONFIRMATION_REJECTED: "CONFIRMATION_REJECTED",
  QUALITY_GATE_FAILED: "QUALITY_GATE_FAILED",
  QUALITY_GATE_REVIEW_REQUIRED: "QUALITY_GATE_REVIEW_REQUIRED",
  QUALITY_GATE_UNKNOWN: "QUALITY_GATE_UNKNOWN",
  REVIEW_REQUIRED: "REVIEW_REQUIRED",
  CRS_NOT_FINALIZED: "CRS_NOT_FINALIZED",
  AXIS_ORDER_INVALID: "AXIS_ORDER_INVALID",
  GEOMETRY_INVALID: "GEOMETRY_INVALID",
  STRUCTURED_GEOMETRY_MISSING: "STRUCTURED_GEOMETRY_MISSING",
  KML_NOT_READY: "KML_NOT_READY",
  RESULT_REVISION_INVALID: "RESULT_REVISION_INVALID",
  RESULT_REVISION_STALE: "RESULT_REVISION_STALE",
  STALE_CONFIRMATION_REVISION: "STALE_CONFIRMATION_REVISION",
  GEOMETRY_HASH_MISMATCH: "GEOMETRY_HASH_MISMATCH",
  CONFIRMATION_RESULT_NOT_FOUND: "CONFIRMATION_RESULT_NOT_FOUND",
  CONFIRMATION_RESULT_EXPIRED: "CONFIRMATION_RESULT_EXPIRED",
  CONFIRMATION_ACTION_INVALID: "CONFIRMATION_ACTION_INVALID",
  SOURCE_AUTHORITY_INVALID: "SOURCE_AUTHORITY_INVALID",
  PROVIDER_EVIDENCE_COVERAGE_INSUFFICIENT: "PROVIDER_EVIDENCE_COVERAGE_INSUFFICIENT",
  FAMILY_BLOCKED_BY_PROVIDER: "FAMILY_BLOCKED_BY_PROVIDER",
  FAMILY_TEMPORARILY_UNAVAILABLE: "FAMILY_TEMPORARILY_UNAVAILABLE",
  DEADLINE_EXCEEDED: "DEADLINE_EXCEEDED"
});

export const FINALIZED_COORDINATE_CRS = Object.freeze({
  id: "EPSG:4326",
  axisOrder: "longitude_latitude"
});

export const FINALIZED_COORDINATE_SOURCE_AUTHORITIES = Object.freeze([
  "legacy",
  "manual_input",
  "coordinate_engine_v2",
  "coordinate_engine_v3"
]);
